title: "{{course_name}}"
author: Aidan Feldman
only_build_toc_files: true
exclude_patterns:
  - .github/*
execute:
  execute_notebooks: "off"
html:
  use_repository_button: true
  extra_navbar: ""
  home_page_in_navbar: false
  extra_footer: |
    <div>
      <a href="https://creativecommons.org/publicdomain/zero/1.0/">
        <img src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg" alt="Creative Commons 0 1.0" />
      </a>
    </div>
repository:
  url: https://github.com/afeld/python-public-policy
  branch: "{{school_slug}}"
launch_buttons:
  binderhub_url: ""
  # this gets overridden; see _static/site.js
  jupyterhub_url: https://padmgp-4506001-fall.rcnyu.org
sphinx:
  config:
    # https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_show_copyright: false
    # https://jupyterbook.org/advanced/html.html#configuring-to-improve-accessibility
    language: en
