name: python-public-policy-jupyter-book
channels:
  # in opposite order from ../environment.yml due to some resolver issue
  - conda-forge
  - defaults
dependencies:
  # this needs to stay in sync with ../environment.yml
  - jupyter-book=0.15.1
