# Locked to environment.lock.yml with:
#
# https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment
#
# After you update this file, run:
#
#   docker compose run jupyter sh -c "conda env export -n base > python-public-policy/extras/environment.lock.yml"
#
name: base
channels:
  - default
  - conda-forge
dependencies:
  # local development
  - RISE
  - jupyter_contrib_nbextensions
  - jupyter-resource-usage
  - nb_conda
  # packages used in notebooks
  - pandas=1.*.*
  - plotly=5.*.*
  - statsmodels=0.*.*
  # https://plotly.com/python/static-image-export/
  - python-kaleido
  # CI
  - nbconvert
  - nbdime
  - pytest
  # other
  - requests
