name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  # local development
  - black
  - nbqa
  - notebook
  - jupyter_contrib_nbextensions
  # extensions
  - ipykernel
  - jupyter-resource-usage
  - nb_conda
  - RISE
  # CI
  - jinja2
  - nbconvert
  - nbdime
  - pytest
  # other
  # this needs to stay in sync with docs/environment.yml
  - jupyter-book=0.13.1
  - requests
