name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  ## local development ##
  - black
  - nbqa
  - notebook=7.*

  # extensions
  - jupyter-resource-usage
  - nb_conda_kernels

  ## packages imported directly in notebooks ##
  # match version in Colab returned by `!python --version`
  - python=3.10.12
  # match versions in Colab returned by `!pip list`
  # required for pandas' read_html()
  - html5lib=1.1
  - lxml
  - pandas=2.1.4
  # newer than what's on Colab, in order to include
  # https://github.com/plotly/plotly.py/pull/4379
  - plotly=5.24.1
  - requests=2.32.3
  - statsmodels=0.14.3
  ## supporting packages for notebooks ##
  # makes kernel available in JupyterHub
  - ipykernel
  - wget
  # https://plotly.com/python/static-image-export/
  - python-kaleido
  # required for plotly rendering
  # https://github.com/plotly/plotly.py/blob/94f2024bc981bdfd3d4ba527122a21286f4c7793/packages/python/plotly/plotly/io/_renderers.py#L395
  - nbformat
  # needed for plotly
  # https://plotly.com/python/getting-started/#jupyterlab-support
  - ipywidgets>=7.6
  - isoduration
  # for AI magic
  - pip
  - pip:
      # https://python.langchain.com/docs/versions/v0_3/#1-do-not-use-the-langchain_corepydantic_v1-namespace
      - langchain-core==0.2.*
      - langchain-openai
      # path/filename may need to be adjusted
      # - ../../rit_jupyter_ai_magics-2.21.0-py3-none-any.whl

  ## CI ##
  - jinja2
  - nbconvert
  - nbdime
  # https://github.com/jupyter/nbconvert/issues/2173
  - pandoc<3.2.1
  - pytest

  # this needs to stay in sync with docs/environment.yml
  - jupyter-book=1.0.3
  # https://github.com/sphinx-doc/sphinx/issues/10440#issuecomment-1556180835
  - sphinx>=6.2.0
