name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  ## local development ##
  - black
  - nbqa
  - notebook

  # extensions
  - ipykernel
  - jupyter-resource-usage
  - nb_conda
  - RISE

  ## packages used in notebooks ##
  - ipytest=0.12.*
  # for QR codes
  - qrcode
  - pillow
  # https://plotly.com/python/static-image-export/
  - python-kaleido
  # match version in Colab returned by `!python --version`
  - python=3.8.10
  # match versions in Colab returned by `!pip list`
  - pandas=1.3.5
  - plotly=5.5.0
  - requests=2.25.1
  # bumped up from Colab, as 0.12.2 was getting `AttributeError: module 'numpy' has no attribute 'MachAr'`
  - statsmodels=0.*.*

  ## CI ##
  - jinja2
  - nbconvert
  - nbdime
  - pytest

  # this needs to stay in sync with docs/environment.yml
  - jupyter-book=0.13.1
