name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  ## local development ##
  - black
  - nbqa
  - notebook=7.*

  # extensions
  - nb_conda_kernels
  - RISE

  ## packages used in notebooks ##
  - ipytest=0.13.*
  - wget
  # https://plotly.com/python/static-image-export/
  - python-kaleido
  # match version in Colab returned by `!python --version`
  - python=3.10.12
  # match versions in Colab returned by `!pip list`
  # required for pandas' read_html()
  - html5lib=1.1
  - lxml
  - pandas=1.5.3
  - plotly=5.15.0
  - requests=2.31.0
  - statsmodels=0.14.0

  ## CI ##
  - jinja2
  - nbconvert
  - nbdime
  - pytest

  # this needs to stay in sync with docs/environment.yml
  - jupyter-book=0.15.1
