name: python-public-policy
channels:
  - default
  - conda-forge
dependencies:
  ## local development ##
  - black
  - nbqa
  - notebook
  # required for nbdime
  - jupyter_server<2.0.0

  # extensions
  - ipykernel
  - jupyter-resource-usage
  - nb_conda
  - RISE

  ## packages used in notebooks ##
  - ipytest=0.13.*
  - wget
  # for QR codes
  - qrcode
  - pillow
  # https://plotly.com/python/static-image-export/
  - python-kaleido
  # match version in Colab returned by `!python --version`
  - python=3.10.6
  # match versions in Colab returned by `!pip list`
  # required for pandas' read_html()
  - html5lib=1.1
  - pandas=1.5.3
  - plotly=5.13.1
  - requests=2.27.1
  - statsmodels=0.13.5

  ## CI ##
  - jinja2
  - nbconvert
  - nbdime
  - pytest

  # this needs to stay in sync with docs/environment.yml
  - jupyter-book=0.13.1
