name: Execute notebooks

on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Run static analysis
        run: python extras/scripts/validate.py

  test:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      # needs to match below, pending https://github.com/actions/runner/issues/646

      # https://github.com/marketplace/actions/setup-miniconda#caching
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if conda-linux-64.lock has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('extras/conda-linux-64.lock') }}
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: python-public-policy
          channel-priority: strict
          environment-file: extras/conda-linux-64.lock
          use-only-tar-bz2: true

      - name: Run tests
        run: pytest

  run_notebook:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        notebook:
          - hw_0.ipynb
          - hw_1.ipynb
          - hw_2.ipynb
          - hw_3.ipynb
          - hw_4.ipynb
          - hw_5.ipynb
          - lecture_0.ipynb
          - lecture_1.ipynb
          - lecture_2.ipynb
          - lecture_3.ipynb
          - lecture_4.ipynb
          - lecture_5.ipynb
          - lecture_6.ipynb
          - extras/pandas_crash_course.ipynb
    steps:
      - uses: actions/checkout@v2

      # needs to match above

      # https://github.com/marketplace/actions/setup-miniconda#caching
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if conda-linux-64.lock has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('extras/conda-linux-64.lock') }}
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: python-public-policy
          channel-priority: strict
          environment-file: extras/conda-linux-64.lock
          use-only-tar-bz2: true

      - name: Confirm notebook hasn't changed
        run: ./extras/scripts/check_change.sh ${{ matrix.notebook }}
