name: Execute notebooks

on: [push]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

  setup:
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows
    uses: ./.github/workflows/setup.yml

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run tests
        run: pytest

  run_notebook:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        notebook:
          - hw_0.ipynb
          - hw_1.ipynb
          - hw_2.ipynb
          - hw_3.ipynb
          - hw_4.ipynb
          - hw_5.ipynb
          - hw_6.ipynb
          - lecture_0.ipynb
          - lecture_1.ipynb
          - lecture_2.ipynb
          - lecture_3.ipynb
          - lecture_4.ipynb
          - lecture_5.ipynb
          - lecture_6.ipynb
          - extras/pandas_crash_course.ipynb
    steps:
      - name: Confirm notebook hasn't changed
        run: ./extras/scripts/check_change.sh ${{ matrix.notebook }}
