name: Execute notebooks

on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Run static analysis
        run: python scripts/validate.py

  run_notebook:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        notebook:
          # - hw_0.ipynb # uses input()s
          - hw_1.ipynb
          - hw_2.ipynb
          # - hw_3.ipynb # has incomplete code
          # - hw_4.ipynb # has incomplete code
          - hw_5.ipynb
          - lecture_0.ipynb
          # - lecture_1.ipynb # uses sample()
          - lecture_2.ipynb
          - lecture_3.ipynb
          - lecture_4.ipynb
          # - lecture_5.ipynb # gets a different .similarity() score locally vs. CI
          # - lecture_5_exercise.ipynb # has incomplete code
          - lecture_6.ipynb
          - jupyter_use.ipynb
          - pandas_crash_course.ipynb
    steps:
      - uses: actions/checkout@v1

      # https://github.com/marketplace/actions/setup-miniconda#caching
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: python-public-policy
          channel-priority: strict
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: Confirm notebook hasn't changed
        run: ./scripts/check_change.sh ${{ matrix.notebook }}
