name: Execute notebooks

on: push

jobs:
  run_notebook:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebook:
          - hw_0.ipynb
          - hw_1.ipynb
          - hw_2.ipynb
          - hw_3.ipynb
          - hw_4.ipynb
          - lecture_0.ipynb
          - lecture_1.ipynb
          - lecture_1_exercise.ipynb
          - lecture_1_exercise_solution.ipynb
          - lecture_2.ipynb
          - lecture_2_exercise.ipynb
          - lecture_3.ipynb
          - lecture_3_exercise.ipynb
          - lecture_3_exercise_solution.ipynb
          - lecture_4.ipynb
          - lecture_5.ipynb
          - lecture_6.ipynb
          - curve.ipynb
          - extras/pandas_crash_course.ipynb
    # https://github.com/mamba-org/provision-with-micromamba#important
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check for changes
        run: ./extras/scripts/check_change.sh ${{ matrix.notebook }}
