name: Execute notebooks

on: push

jobs:
  run_notebook:
    strategy:
      fail-fast: false
      matrix:
        notebook:
          - hw_0.ipynb
          - hw_1.ipynb
          - hw_2.ipynb
          - hw_3.ipynb
          - hw_4.ipynb
          - final_project.ipynb
          - hw_5_old.ipynb
          - lecture_0.ipynb
          - lecture_1.ipynb
          - lecture_2.ipynb
          - lecture_3.ipynb
          - lecture_4.ipynb
          - lecture_5.ipynb
          - lecture_6.ipynb
          - extras/pandas_crash_course.ipynb
    uses: ./.github/workflows/setup.yml
    with:
      message: Check for changes
      command: ./extras/scripts/check_change.sh ${{ matrix.notebook }}
