name: Publish school-specific branches / site versions
on: push
# cancel any previous builds
concurrency:
  group: schools-${{ github.ref }}
  cancel-in-progress: true
jobs:
  schools:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        school:
          - columbia
          - nyu
    # https://github.com/mamba-org/provision-with-micromamba#important
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      # avoid force pushes on school branches by merging main but then only committing the processed files
      - name: Merge into school branch
        run: |
          git checkout -b ${{ matrix.school }}-merged
          git merge -s ours --no-commit --no-ff ${{github.ref_name}}
          # https://stackoverflow.com/a/68636946/358804
          git restore --source ${{github.ref_name}} --worktree --staged -- .
      - name: Render for school
        run: ./extras/scripts/school_ci.sh ${{ matrix.school }}
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "alf9@nyu.edu"
          git add -A
          git commit -am "CI: render for school"
      - name: Push branch
        run: git push origin ${{ matrix.school }}-merged
      - name: Store rendered HTML for link checking
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.school }}
          path: _build/html
  # do this as a separate job from link checking so that broken external links don't block the site build
  check_links:
    runs-on: ubuntu-latest
    needs: schools
    strategy:
      fail-fast: false
      matrix:
        school:
          - columbia
          - nyu
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
      - name: Install dependencies
        run: gem install html-proofer

      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.school }}
          path: _build/html

      - name: Check for broken links
        run: ruby extras/scripts/broken_links.rb
