name: Publish school-specific branches / site versions
on: push
# cancel any previous builds
concurrency:
  group: schools-${{ github.ref }}
  cancel-in-progress: true
jobs:
  schools:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        school:
          - columbia
          - nyu
    # https://github.com/mamba-org/provision-with-micromamba#important
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: ./.github/actions/setup
      - name: Render for school
        run: ./extras/scripts/school_ci.sh ${{ matrix.school }}
