name: Publish school-specific branches / site versions
on: push
# cancel any previous builds
concurrency:
  group: schools-${{ github.ref }}
  cancel-in-progress: true
jobs:
  schools:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        school:
          - columbia
          - nyu
    # https://github.com/mamba-org/provision-with-micromamba#important
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Render for school
        run: ./extras/scripts/school_ci.sh ${{ matrix.school }}
      - name: Push branch
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          target_branch: ${{ matrix.school }}
          commit_message: "CI: render for school"
          force: true
        if: github.ref_name == 'main'
      - name: Store rendered HTML for link checking
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.school }}
          path: _build/html
  check_links:
    runs-on: ubuntu-latest
    needs: schools
    strategy:
      fail-fast: false
      matrix:
        school:
          - columbia
          - nyu
    steps:
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
      - name: Install dependencies
        run: gem install html-proofer

      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.school }}
          path: _build/html

      - name: Check for broken links
        run: ruby extras/scripts/broken_links.rb
