on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      command:
        required: true
        type: string

jobs:
  run-in-conda:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda packages
        uses: mamba-org/provision-with-micromamba@main
        with:
          channel-priority: strict
          environment-file: extras/environment.yml
          cache-downloads: true
          cache-env: true
      - name: ${{ inputs.message }}
        run: ${{ inputs.command }}
