on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/setup-miniconda#caching
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('extras/environment.yml') }}
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: python-public-policy
          channel-priority: strict
          environment-file: extras/environment.yml
          use-only-tar-bz2: true
