# https://docs.github.com/en/actions/using-workflows/reusing-workflows

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      command:
        required: true
        type: string

jobs:
  run-in-conda:
    runs-on: ubuntu-latest
    # https://github.com/mamba-org/provision-with-micromamba#important
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda packages
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: extras/environment.yml
          init-shell: bash
          cache-environment: true
      # needed for htmlproofer
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3"
      - name: ${{ inputs.message }}
        run: ${{ inputs.command }}
